# Coleta e preparação de dados

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install pandas==2.0.0

Collecting pandas==2.0.0
  Downloading pandas-2.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.0) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.0) (2025.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.11/dist-packages (from pandas==2.0.0) (1.26.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas==2.0.0) (1.17.0)
Downloading pandas-2.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 44.4 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.0.0 which is incompatible.
plotnine 0.14.5 requires pandas>=2.2.0, but you have pandas 2.0.0 which is incompatible.
xarray 2025.1.1 requires pandas>=2.1, but you have pandas 2.0.0 which is incompatible.
mizani 0.13.1 requires pandas>=2.2.0, but you have pandas 2.0.0 which is incompatible.
Successfully installed pandas-2.0.0

In [ ]:
import pandas as pd
vendas = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Avançando em Data Science com Python/Dados/relatorio_vendas.csv')
vendas.head()

,data_pedido,data_envio,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,preco_base,preco_unit_sem_desc,desconto,preco_unit_venda,quantidade,vendas,lucro
0,2018-11-09,2018-11-12,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,encanamentos,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,ferramentas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Econômica,Giovanna Lima,B2B,Rio de Janeiro,Rio de Janeiro,Sudeste,Jardinagem e paisagismo,sementes,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Materiais de construção,materiais de revestimento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Jardinagem e paisagismo,vasos,35.88,42.24,0.100,38.02,2,76.04,4.28

In [ ]:
vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data_pedido          8940 non-null   object
 1   data_envio           8940 non-null   object
 2   modo_envio           8940 non-null   object
 3   nome_cliente         8940 non-null   object
 4   segmento_cliente     8940 non-null   object
 5   cidade               8940 non-null   object
 6   estado               8940 non-null   object
 7   regiao               8940 non-null   object
 8   departamento         8940 non-null   object
 9   tipo_produto         8940 non-null   object
 10  preco_base           8940 non-null   float64
 11  preco_unit_sem_desc  8940 non-null   float64
 12  desconto             8940 non-null   float64
 13  preco_unit_venda     8940 non-null   float64
 14  quantidade           8940 non-null   int64
 15  vendas               8940 non-null   float64
 16  lucro                8940 non-null   float64
dtypes: float64(6), int64(1), object(10)
memory usage: 1.2+ MB

In [ ]:
vendas = vendas.drop(["data_envio"], axis=1)
vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   quantidade        8940 non-null   int64
 10  vendas            8940 non-null   float64
 11  lucro             8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.3+ KB

In [ ]:
vendas['data_pedido'] = pd.to_datetime(vendas['data_pedido'])
vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   quantidade        8940 non-null   int64
 10  vendas            8940 non-null   float64
 11  lucro             8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.3+ KB

In [ ]:
valores_data = vendas['data_pedido'].unique()
valores_data

<DatetimeArray>
['2018-11-09 00:00:00', '2018-06-13 00:00:00', '2017-10-12 00:00:00',
 '2016-06-10 00:00:00', '2019-04-16 00:00:00', '2018-12-06 00:00:00',
 '2017-11-23 00:00:00', '2016-11-12 00:00:00', '2016-08-28 00:00:00',
 '2018-12-10 00:00:00',
 ...
 '2016-06-19 00:00:00', '2019-03-01 00:00:00', '2017-05-10 00:00:00',
 '2016-11-07 00:00:00', '2017-12-30 00:00:00', '2016-04-04 00:00:00',
 '2016-01-24 00:00:00', '2018-06-04 00:00:00', '2017-04-13 00:00:00',
 '2016-01-22 00:00:00']
Length: 1209, dtype: datetime64[ns]

# Missão 1: Time de vendas

Precisamos construir uma visualização para indicar os **10 maiores clientes por total de venda**.

Com isso, a equipe de vendas pode pensar em estratégias para manter esses clientes comprando em nossa loja.

In [ ]:
df_cliente_vendas = vendas.groupby(['nome_cliente'])['vendas'].sum().nlargest(10).copy()

In [ ]:
df_cliente_vendas = df_cliente_vendas.reset_index()

In [ ]:
df_cliente_vendas

            nome_cliente    vendas
0    Maria Luiza Almeida  64777.52
1        Ana Julia Pinto  51398.87
2            Ryan Farias  48178.99
3         Heitor da Mata  47610.80
4  Maria Clara Gonçalves  46946.38
5         Raquel Freitas  44826.25
6             Davi Ramos  43769.25
7            Amanda Melo  42354.19
8         Alexia Ribeiro  41238.81
9         Calebe Ribeiro  41056.80

In [ ]:
df_cliente_vendas.columns = ['Clientes', 'Vendas']
df_cliente_vendas['Ranque'] = df_cliente_vendas.index + 1
df_cliente_vendas.set_index('Ranque', inplace=True)
df_cliente_vendas

                     Clientes    Vendas
Ranque
1         Maria Luiza Almeida  64777.52
2             Ana Julia Pinto  51398.87
3                 Ryan Farias  48178.99
4              Heitor da Mata  47610.80
5       Maria Clara Gonçalves  46946.38
6              Raquel Freitas  44826.25
7                  Davi Ramos  43769.25
8                 Amanda Melo  42354.19
9              Alexia Ribeiro  41238.81
10             Calebe Ribeiro  41056.80

# Transformando o dataframe em um objeto style

In [ ]:
s = df_cliente_vendas.style
s

In [ ]:
s.format({'Vendas':'R$ {:,.2f}'})
s

### DESAFIO AULA 1

* Construir uma visualização que permita identificar quais países mais solicitaram produtos por pedidos para que assim possa ser feito um estudo quanto a distribuição e logística de produtos.

In [ ]:
import pandas as pd

livro_filmes = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Avançando em Data Science com Python/Dados/loja_livro_filmes.csv')
livro_filmes.head()

,pais,id_cliente,data_pedido,data_chegada,tipo_compra,numero_pedido,tamanho_pacote,unidades,custo_empacotamento,custo_envio,tipo_desconto,categoria,tipo_consumo,tipo_cliente,custo_produto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Pacote pequeno,1,3.0,5.99,Sem desconto,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Pacote pequeno,3,1.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Pacote pequeno,1,3.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolução,98077986,Pacote pequeno,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Pacote pequeno,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88

In [ ]:
livro_filmes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24890 entries, 0 to 24889
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pais                 24890 non-null  object
 1   id_cliente           24890 non-null  int64
 2   data_pedido          24890 non-null  object
 3   data_chegada         24890 non-null  object
 4   tipo_compra          24890 non-null  object
 5   numero_pedido        24890 non-null  int64
 6   tamanho_pacote       24890 non-null  object
 7   unidades             24890 non-null  int64
 8   custo_empacotamento  24890 non-null  float64
 9   custo_envio          24890 non-null  float64
 10  tipo_desconto        24890 non-null  object
 11  categoria            24890 non-null  object
 12  tipo_consumo         24890 non-null  object
 13  tipo_cliente         24890 non-null  object
 14  custo_produto        24890 non-null  float64
dtypes: float64(3), int64(3), object(9)
memory usage: 2.8+ MB

In [ ]:
# Agrupar a soma das unidades por pais e ordenar os valores
df_pedido_pais = livro_filmes.groupby(['pais'])['unidades'].sum().nlargest(5).copy()
df_pedido_pais = df_pedido_pais.reset_index()
df_pedido_pais

        pais  unidades
0  Argentina      5591
1    Equador      5566
2   Paraguai      5564
3       Peru      5550
4  Venezuela      5529

In [ ]:
df_pedido_pais.columns = ['Pais', 'Unidades']
df_pedido_pais['Ranque'] = df_pedido_pais.index + 1
df_pedido_pais.set_index('Ranque', inplace=True)
df_pedido_pais

             Pais  Unidades
Ranque
2       Argentina      5591
3         Equador      5566
4        Paraguai      5564
5            Peru      5550
6       Venezuela      5529

In [ ]:
s = df_pedido_pais.style
s

In [ ]:
# Formatar o texto para adicionar a unidade de medida
s= s.format({'Unidades': '{} prod'})
s

# Missão 2: Time comercial

Precisamos construir uma visualização que permita associar o **total ganho em vendas e o total lucrado por tipo de produto**.

Isso vai permitir que o time comercial possa focar em estratégias para alavancar as rendas que ganham com cada tipo de produto vendido na loja.

In [ ]:
df_venda_lucro = vendas.groupby(['tipo_produto'])[['vendas', 'lucro']].sum().copy()
df_venda_lucro.index.name = 'Tipo de produto'
df_venda_lucro.sort_values(by='lucro', ascending=False, inplace=True)
df_venda_lucro

                               vendas     lucro
Tipo de produto
peças de reposição          486907.94  91148.67
pneus                      1022428.97  67460.05
ferramentas automotivas     502109.29  63330.22
pesticidas                  244956.04  53343.89
ferramentas de jardinagem   648879.72  53202.88
ferramentas                 995158.41  41020.34
vasos                       696044.18  33941.85
mobiliário de exterior      328932.27  26784.59
iluminação                  275229.53  20264.54
fertilizantes                53144.74  11254.88
decoração de jardim          82680.08   9939.43
sementes                     39979.75   8865.09
equipamentos de limpeza     542304.58   8724.39
mudas                         8811.32   1381.42
materiais de paisagismo     150552.49  -1912.37
encanamentos                373223.88  -5622.34
materiais de revestimento   629656.36 -28869.01

In [ ]:
estilo_produto = df_venda_lucro.style
estilo_produto

In [ ]:
estilo_produto = estilo_produto.format({'vendas': 'R$ {:,.2f}', 'lucro': 'R$ {:,.2f}'})\
                              .highlight_max(color='lightgreen')\
                              .highlight_min(color='#F16165')
estilo_produto

In [ ]:
estilo_produto.format('R$ {:,.2f}').background_gradient(subset='lucro',cmap='Greens')\
              .background_gradient(subset='vendas', cmap='Blues')
estilo_produto

In [ ]:
cabecalho = {
    'selector': 'th', # seleciona o index e o cabeçalho
    'props': 'font-weight: bold; font-family: Arial; text-align: center; text-transform:capitalize;' # altera o estilo do texto
  }
estilo_produto.set_table_styles([cabecalho], overwrite=False)

### DESAFIO AULA 2
* Construir uma visualização que permita identificar quais categorias de produto geraram mais e menos custos para a loja.

In [ ]:
livro_filmes.head()

,pais,id_cliente,data_pedido,data_chegada,tipo_compra,numero_pedido,tamanho_pacote,unidades,custo_empacotamento,custo_envio,tipo_desconto,categoria,tipo_consumo,tipo_cliente,custo_produto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Pacote pequeno,1,3.0,5.99,Sem desconto,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Pacote pequeno,3,1.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Pacote pequeno,1,3.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolução,98077986,Pacote pequeno,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Pacote pequeno,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88

In [ ]:
desafio2 = livro_filmes.groupby(['categoria'])['custo_produto'].sum().nlargest(5).copy()
desafio2 = desafio2.reset_index()
desafio2

  categoria  custo_produto
0     Livro       78213.80
1   Coleção       73128.59
2   BlueRay       14191.36
3        CD       10514.28

In [ ]:
estilo_desafio2 = desafio2.style
estilo_desafio2

In [ ]:
## Importar o pandas e ler o arquivo
## Preparar os dados
# Agrupar a soma dos custos dos pedidos por categoria
df_produto_custo = livro_filmes.groupby(['categoria'])[['custo_produto']].sum()
# Ajustar o nome da coluna e index
df_produto_custo.index.name = 'Categoria produto'
df_produto_custo.columns = ['Custo de pedidos']
df_produto_custo

## Criar a visualização
s_produto = df_produto_custo.style
# Destacar elementos
s_produto.format('R$ {:,.2f}')\
         .highlight_max(color='#F16165')\
         .highlight_min(color='lightgreen')

# Missão 3: Time de logística

Precisamos construir uma visualização que permita entender a **distribuição de pedidos por região do Brasil**.

Isso vai permitir que o time logística entenda onde é mais interessante focar material e pessoas.

In [ ]:
df_regiao = pd.DataFrame(vendas['regiao'].value_counts())
df_regiao.columns = ['Nº pedidos']
df_regiao

              Nº pedidos
regiao
Sudeste             4470
Nordeste            2075
Centro-Oeste         983
Norte                779
Sul                  633

In [ ]:
df_regiao.index.name = 'Região'
df_regiao

              Nº pedidos
Região
Sudeste             4470
Nordeste            2075
Centro-Oeste         983
Norte                779
Sul                  633

In [ ]:
import numpy as np

In [ ]:
porcentagem = df_regiao['Nº pedidos'].to_numpy()
porcentagem = 100*porcentagem / porcentagem.sum()
df_regiao['Porcentagem região'] = np.round(porcentagem, decimals=2)
df_regiao

              Nº pedidos  Porcentagem região
Região
Sudeste             4470               50.00
Nordeste            2075               23.21
Centro-Oeste         983               11.00
Norte                779                8.71
Sul                  633                7.08

In [ ]:
df_regiao.sort_values(by='Nº pedidos', ascending=False, inplace=True)
df_regiao

              Nº pedidos  Porcentagem região
Região
Sudeste             4470               50.00
Nordeste            2075               23.21
Centro-Oeste         983               11.00
Norte                779                8.71
Sul                  633                7.08

In [ ]:
estilo_regiao = df_regiao.style
estilo_regiao

In [ ]:
cabecalho = {
    'selector': 'th',
    'props': 'font-weight: bold; font-family: Times; text-align: center; text-transform:capitalize;; background-color:white'
  }
celulas = {
      'selector': 'td',
      'props': 'text-align: center; background-color:white'
  }
estilo_regiao.set_table_styles([cabecalho],[celulas])

In [ ]:
estilo_regiao.format({'Porcentagem região': '{:.2f}%'})\
              .bar(subset='Porcentagem região', vmin=0, vmax=100, color='#9CCD33B')
estilo_regiao

### DESAFIO AULA 3

* Construir uma visualização que permita informar a quantidade e distribuição de pedidos por tipo de desconto.

In [ ]:
## Preparar os dados
# Ter o DataFrame fazendo a contagem dos pedidos em cada categoria de desconto
df_descontos = pd.DataFrame(livro_filmes['tipo_desconto'].value_counts())
# Ajustar o nome da coluna e index
df_descontos.columns = ['N° pedidos']
df_descontos.index.name = 'Tipo desconto'
# Coletamos a distribuição da quantidade de pedidos por porcentagem
porcentagem = df_descontos['N° pedidos'].to_numpy()
porcentagem = 100 * porcentagem/porcentagem.sum()
df_descontos['Distribuição de pedidos'] = porcentagem
df_descontos

## Criar a visualização
s_descontos = df_descontos.style
# Utilizar propriedades CSS para formatar a visualização
cabecalho = {
    'selector': 'th',
    'props': 'font-weight: bold; font-family: Arial; text-align: right; background-color: white; color: black;'
}
celulas = {
    'selector': 'td',
    'props': 'background-color: white; color: black;'
}
s_descontos.set_table_styles([cabecalho, celulas], overwrite=False)
# Aplicar a visualização de gráfico
# os parâmetros height e width permitem alterar a proporção do tamanho do gráfico em relação a padrão 100
s_descontos.format({'Distribuição de pedidos': '{:.2f} %'})\
           .bar(subset='Distribuição de pedidos', vmin = 0, vmax = 100.0, color = '#093364',
                height=50,width=60)

# Missão 4: Time de logística

Novamente o time de logística deseja repensar sua estrutura e organização de fornecimento de produtos e para isso, foi pensada em uma visualização que permita identificar padrão de **quantidade de produtos solicitados por mês por departamento**.

In [ ]:
df_meses = vendas.copy()
df_meses = df_meses.sort_values('data_pedido')
df_meses

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,quantidade,vendas,lucro
7171,2016-01-04,Entrega padrão,Ana Júlia Monteiro,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,pesticidas,2,55.92,9.44
651,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,2,12.04,-9.32
650,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,vasos,3,927.30,-110.13
649,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,sementes,3,40.08,7.26
1576,2016-01-06,Entrega padrão,Marcelo Rezende,B2C,Brasília,Distrito Federal,Centro-Oeste,Jardinagem e paisagismo,decoração de jardim,3,66.42,8.31
...,...,...,...,...,...,...,...,...,...,...,...,...
796,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,3,179.43,33.63
795,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Automotivo,pneus,7,309.19,4.69
794,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Materiais de construção,encanamentos,4,1098.68,20.60
1151,2019-12-31,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,2,47.28,7.68
1152,2019-12-31,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,2,70.44,11.00

In [ ]:
df_meses['meses'] = df_meses['data_pedido'].dt.strftime('%Y-%b')
df_meses = df_meses.reset_index(drop=True)
df_meses

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,quantidade,vendas,lucro,meses
0,2016-01-04,Entrega padrão,Ana Júlia Monteiro,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,pesticidas,2,55.92,9.44,2016-Jan
1,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,2,12.04,-9.32,2016-Jan
2,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,vasos,3,927.30,-110.13,2016-Jan
3,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,sementes,3,40.08,7.26,2016-Jan
4,2016-01-06,Entrega padrão,Marcelo Rezende,B2C,Brasília,Distrito Federal,Centro-Oeste,Jardinagem e paisagismo,decoração de jardim,3,66.42,8.31,2016-Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,3,179.43,33.63,2019-Dec
8936,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Automotivo,pneus,7,309.19,4.69,2019-Dec
8937,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Materiais de construção,encanamentos,4,1098.68,20.60,2019-Dec
8938,2019-12-31,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,2,47.28,7.68,2019-Dec
8939,2019-12-31,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,2,70.44,11.00,2019-Dec

In [ ]:
# Construindo uma tabela dinâmica por pivot table

In [ ]:
vendas_mensais = df_meses.pivot_table(index='departamento', columns='meses', values='quantidade',
                                      aggfunc='sum', sort=False)
vendas_mensais

meses,2016-Jan,2016-Feb,2016-Mar,2016-Apr,2016-May,2016-Jun,2016-Jul,2016-Aug,2016-Sep,2016-Oct,...,2019-Mar,2019-Apr,2019-May,2019-Jun,2019-Jul,2019-Aug,2019-Sep,2019-Oct,2019-Nov,2019-Dec
departamento,,,,,,,,,,,,,,,,,,,,,
Jardinagem e paisagismo,161,87,277,323,270,273,348,339,549,276,...,458,415,542,490,423,561,929,617,946,989
Automotivo,45,20,46,107,81,83,91,95,154,85,...,167,87,150,170,168,136,280,205,331,252
Materiais de construção,60,23,102,69,91,114,104,101,182,94,...,107,131,172,151,162,132,282,213,312,395

In [ ]:
estilo_mensal= vendas_mensais.style
estilo_mensal

In [ ]:
# Fixando a coluna de index (congelar painel no excel)
estilo_mensal.set_sticky(axis = 'index')

In [ ]:
colunas = {
    'selector': '.col_heading',
    'props': 'font-weight: normal; font-family: Arial'
}
tabelas = {
    'selector': 'td,th',
    'props': 'text-align: left;'
}
index = {
    'selector': '.index_name',
    'props': 'font-weight: bold; font-family: Arial; text-align: right;'
}
estilo_mensal.set_table_styles([colunas,tabelas,index],overwrite=False)

### DESAFIO AULA 4
* Fornecer uma visualização que permita mostrar o tempo médio de entrega de pedidos durante os meses dos anos de 2013 a 2015 por cada país

In [ ]:
# Tornar 'data_chegada' e 'data_pedido' colunas datetime
livro_filmes['data_chegada'] = pd.to_datetime(livro_filmes['data_chegada'])
livro_filmes['data_pedido'] = pd.to_datetime(livro_filmes['data_pedido'])

## Construir cópia de um DataFrame para adicionar novas colunas de dados
df_datas = livro_filmes.copy()
df_datas = df_datas.sort_values('data_pedido')
df_datas = df_datas.reset_index(drop=True)

# Coletar apenas informações a partir do ano de 2013
df_datas = df_datas[df_datas['data_pedido'] >= '2013-01-01']

# Adicionar coluna com os meses formatados
df_datas['meses'] = df_datas['data_pedido'].dt.strftime('%Y - %b')

# Adicionar uma coluna com o tempo de entrega entre pedido e chegada
tempo_demora = (df_datas['data_chegada'] - df_datas['data_pedido']).dt.days
df_datas['tempo_entrega'] = tempo_demora

# Criar a estrutura em DataFrame
entregas = df_datas.pivot_table(index = 'pais', columns = 'meses', values = 'tempo_entrega' , aggfunc = 'mean', sort=False)

## Criar a visualização
s_entregas = entregas.style.format('{:,.2f}')
s_entregas.set_sticky(axis="index")

# Missão 5: Relatório de performance

O relatório de performance é um documento muito importante para a empresa. Nele, todos que trabalham na loja podem entender como anda a empresa. Por conta disso, tabelas bem construídas são essenciais para mostrar os dados da melhor forma.

Portanto, precisamos construir uma visualização que permita entender a **relação entre tipos de clientes e modo de envio de produtos de acordo com as vendas**. Com isso, será possível destacar no relatório qual o modo de envio e quais tipos de modo de envio mais geraram ganho em vendas.

In [ ]:
df_cliente = vendas.pivot_table(index='segmento_cliente', columns='modo_envio', values='vendas',
                                aggfunc='sum')
df_cliente

modo_envio         24 horas  Econômica  Entrega padrão  Envio rápido
segmento_cliente
B2B               217465.60  718461.22      1884738.56     602049.40
B2C               182531.47  729174.73      2248283.69     498294.88

In [ ]:
df_cliente['Total'] = df_cliente.sum(axis=1)
df_cliente.loc['Total'] = df_cliente.sum()
df_cliente

modo_envio,24 horas,Econômica,Entrega padrão,Envio rápido,Total
segmento_cliente,,,,,
B2B,217465.60,718461.22,1884738.56,602049.40,6845429.56
B2C,182531.47,729174.73,2248283.69,498294.88,7316569.54
Total,399997.07,1447635.95,4133022.25,1100344.28,14161999.10

In [ ]:
compra_cliente = df_cliente.style.format('{:,.2f}')
compra_cliente

In [ ]:
tabela = {
    'selector': 'td,th:not(.index_name)',
    'props': 'text-align: center; font-family: Times; background-color: white',
}
index = {
    'selector': '.index_name',
    'props': 'font-weight: normal; font-family: Times; text-align: right; background-color: white; font-style:italic; color: white'
}
compra_cliente.set_table_styles([tabela, index])

In [ ]:
compra_cliente.set_table_styles({
    'Total': [{
        'selector': 'th',
        'props': 'border-top: 1px solid #181818 '
    },
    {
        'selector': 'td',
        'props': 'border-top: 1px solid #181818 '
    }],
    'B2B': [{
        'selector': 'th',
        'props': 'border-top: 1px solid #181818 '
    },
    {
        'selector': 'td',
        'props': 'border-top: 1px solid #181818 '
    }]
}, overwrite=False, axis=1)

In [ ]:
compra_cliente.set_table_styles({
    'Total': [{
        'selector': '.true',
        'props': 'background-color: lightgreen'
    }]
}, overwrite=False, axis=0)

In [ ]:
cores_coluna = pd.DataFrame(['false', 'true', 'false'], index= df_cliente['Total'].index, columns=['Total'])
compra_cliente.set_td_classes(cores_coluna)

In [ ]:
compra_cliente.set_table_styles({
    'Total': [{'selector': '.true', 'props': 'background-color: lightgreen;'}]
}, overwrite=False, axis=1)

cores_linha = pd.DataFrame([['false', 'false', 'false', 'false', 'true']],
                            columns=df_cliente.columns,
                            index=['Total'])

compra_cliente.set_td_classes(cores_linha)

### DESAFIO AULA 5

*  Uma visualização que permita separar os gastos de envio de cada produto (custo total) por tipo de cliente, de modo que seja possível entender o tipo de produto que mais gerou custos de envio em cada tipo de cliente. Além disso, é interessante também mostrar a distribuição desses custos por país enviado, permitindo entender também os gastos por país.

In [ ]:
## Importar o pandas e ler o arquivo
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Avançando em Data Science com Python/Dados/loja_livro_filmes.csv')

## Preparar os dados

# Criar um DataFrame alternativo para ter um nome de coluna coerente com a visualização
df_alteracao = df.rename(columns={'pais': 'Custo por país ($)'})

# Agrupar os dados de tipo de cliente, com a categoria de produtos e os países que esses clientes importam o produto
df_clientes = df_alteracao.pivot_table(index=['tipo_cliente', 'categoria'], columns = 'Custo por país ($)', values = 'custo_produto', aggfunc = 'sum')

# Renomear o cabeçalho para nomes mais coerentes
df_clientes.rename_axis(index={'tipo_cliente': 'Tipo cliente', 'categoria': 'Categoria produto'}, inplace = True)

# Adicionar uma coluna que mostra a soma dos custos por tipo de cliente e categoria de produto
df_clientes['Total ($)'] = df_clientes.sum(axis=1)

## Criar a visualização
s_clientes = df_clientes.style.format('{:,.2f}')

# Criar os estilos base para a tabela, a partir da padronização das fontes, plano de fundo para branco e o alinhamento do cabeçalho para o topo
tabela = {
    'selector': 'td, th',
    'props': 'font-weight: normal; font-family: Arial; text-align: right; background-color: white;'
}
# Alinhar verticalmente o cabeçalho para o topo permite a pessoa observadora identificar onde começa a hierarquização dos grupos B2B e B2C
cabecalho = {
    'selector': 'th',
    'props': 'vertical-align: top'
}
s_clientes.set_table_styles([tabela, cabecalho])

# Adicionar linha de separação do cabeçalho superior
# Destacar as categorias que mais geraram custo com a aplicação de negrito nas fontes
s_clientes.set_table_styles({
    ('B2B', 'BlueRay'): [{'selector': 'th', 'props': 'border-top: 1px solid #181818'},
              {'selector': 'td', 'props': 'border-top: 1px solid #181818'}],
    ('B2B', 'Livro'): [{'selector': 'th', 'props': 'font-weight: bold'}],
    ('B2C', 'Livro'): [{'selector': 'th', 'props': 'font-weight: bold'}],
}, overwrite=False, axis=1)

# Destacar os elementos em cada tipo de cliente que mais geraram custos com uma seleção
s_clientes.set_table_styles({
    'Total ($)': [{
        'selector': '.true',
        'props': 'font-weight: bold'
    }]
},overwrite=False,axis=0)

cores_coluna = pd.DataFrame(['false','false','false','true','false','false','false','true'],index= df_clientes['Total ($)'].index,
                            columns = ['Total ($)'])
# Visualização final
s_clientes.set_td_classes(cores_coluna)